language: node_js
node_js: stable
 
# S: Build Lifecycle
install:
  - npm install
  - npm run dist
 
script:
  - hexo g
 
after_script:
  - cd ./public
  - git init
  - git config user.name "TMs"
  - git config user.email "tms@live.cn"
  - git add .
  - git commit -m "Update"
  - git push --force --quiet "https://${TOKEN}@github.com/imtms/imtms.github.io.git" master:master
# E: Build LifeCycle
 
branches:
  only:
    - blog-source
