language: node_js
node_js:
  - '22'
cache: npm

install:
  - npm ci

script:
  - npm run build

after_success:
  - cd public
  - git init
  - git config user.name "TMs"
  - git config user.email "tms@live.cn"
  - git add .
  - git commit -m "Update"
  - git push --force --quiet "https://${TOKEN}@github.com/imtms/imtms.github.io.git" master:master

branches:
  only:
    - blog-source
