version: 5.1.0
variant: default
logo: /TMs.png

head:
  favicon: /favicon.ico
  manifest:
    name: TMs
    short_name: TMs
    start_url: /
    theme_color: '#f7f8fa'
    background_color: '#f7f8fa'
    display: standalone
    icons:
      - src: /favicon.ico
        sizes: 32x32
        type: image/x-icon
  open_graph:
    image: /TMs.png
    site_name: TMs
    author: TMs
    twitter_card: summary_large_image
  structured_data:
    publisher: TMs
    publisher_logo: /TMs.png
  meta:
    - name=theme-color;content=#f7f8fa
  rss: null

navbar:
  menu:
    首页: /
    归档: /archives
    分类: /categories
    标签: /tags
    关于: https://tms.im
  links:
    博客源码:
      icon: fab fa-github
      url: https://github.com/imtms/blog-source

article:
  highlight:
    theme: atom-one-light
    clipboard: true
    fold: unfolded
  readtime: true
  update_time: auto
  licenses:
    Creative Commons:
      icon: fab fa-creative-commons
      url: https://creativecommons.org/
    Attribution:
      icon: fab fa-creative-commons-by
      url: https://creativecommons.org/licenses/by/4.0/
    Noncommercial:
      icon: fab fa-creative-commons-nc
      url: https://creativecommons.org/licenses/by-nc/4.0/

search:
  type: insight
  index_pages: true

comment:
  type: disqus
  shortname: xtms

sidebar:
  right:
    sticky: true

widgets:
  - position: left
    type: profile
    author: TMs
    location: Earth
    avatar: /TMs.png
    avatar_rounded: false
  - position: left
    type: categories
  - position: left
    type: recent_posts

plugins:
  animejs: false
  back_to_top: true
  gallery: true
  katex: false
  mathjax: false
  outdated_browser: false
  pjax: false
  progressbar: false

providers:
  cdn: jsdelivr
  fontcdn: /css/fonts.css
  iconcdn: fontawesome
